/* Autogenerated file. Do not edit manually. */
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from "./IERC20";

export { IERC20__factory } from "./factories/IERC20__factory";
